services:

  matomo-app:
    image: docker.io/nfrastack/matomo
    container_name: matomo-app
    links:
      - matomo-db
    labels:
      - traefik.enable=true
      - traefik.http.routers.matomo.rule=Host(`matomo.example.com`)
      - traefik.http.services.matomo.loadbalancer.server.port=80
    volumes:
      - ./data:/www/html
      - ./logs/:/www/logs
    environment:
      - TIMEZONE=America/Vancouver

      - DB_HOST=matomo-db
      - DB_NAME=matomo
      - DB_USER=matomo
      - DB_PASS=userpassword

      - CRON_PERIOD=60
    networks:
      - proxy
      - services
    restart: always

  matomo-db:
    image: docker.io/nfrastack/mariadb:11.8
    container_name: matomo-db
    volumes:
      - /var/local/db/matomo:/data
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=matomo-db

      - ROOT_PASS=password
      - DB_NAME=matomo
      - DB_USER=matomo
      - DB_PASS=userpassword
    networks:
      - services
    restart: always

  matomo-db-redis:
    image: docker.io/nfrastack/redis:latest
    container_name: matomo-db-redis
    environment:
      - TIMEZONE=America/Vancouver
    networks:
      - services
    restart: always

  matomo-db-backup:
    image: docker.io/tiredofit/db-backup
    container_name: matomo-db-backup
    links:
      - matomo-db
    volumes:
      - ./dbbackup:/backup
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=matomo-db-backup
      - DB01_HOST=matomo-db
      - DB01_TYPE=mysql
      - DB01_NAME=matomo
      - DB01_USER=matomo
      - DB01_PASS=userpassword
      - DB01_BACKUP_INTERVAL=1440
      - DB01_BACKUP_BEGIN=0000
      - DB01_CLEANUP_TIME=8640
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
